### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by wilhelmklopp** [wilhelmklopp/exam-revision-2017#1]
# Revision plan

Let's go revise 🚨 🎉 🌮 👨‍🎓 🍾 💻 💯 

**27/04**
- [x] Case Study
- [x] Mastering Week 1
- [x] Mastering Week 2
- [x] Mastering Week 3
- [x] Mastering Week 4

**28/04**
- [x] Mastering Week 5
- [x] Mastering Week 6
- [x] Mastering Week 7
- [x] Mastering Week 8
- [x] Mastering Week 9
- [x] Mastering Week 10
- [x] One past paper

**29/04**

- [x]  Go through fancy revision notes
- [x] Other past papers
- [x] Other reading:
![image](https://cloud.githubusercontent.com/assets/7718702/25484449/0077d43e-2b52-11e7-9f67-8d8251503bd2.png)

**01/05**

- [ ] prepare Answer for final section question
- [x] Competitive Week 1
- [x] Competitive Week 2
- [x] Competitive Week 3
- [x] Competitive Week 4
- [x] Competitive Week 5
- [ ]  Go through fancy revision notes

**02/05**

- [x] Competitive Week 6
- [x] Competitive Week 7
- [x] Competitive Week 8
- [x] Competitive Week 9
- [x] Competitive Week 10
- [ ] Do past papers

**03/05**
- [x] Go over all Mastering stuff again
- [x] Find a bunch of fancy examples to read and reference in the exam
- [x] Watch all guest lectures

**04/05**
- [ ] More past papers
- [ ] pre-write exam answers based on structure
- [ ] refine answer for final section
- [ ] Go through Moodle Exam Resources section

**Comment by danielgavrilov** [comment]
29/04: maybe i should start ticking some of these boxes...
02/05: oh my god so many boxes
04/05: oh my god

**Comment by wilhelmklopp** [comment]
Exam update: First one went pretty well. Next one tomorrow :)

**Comment by wilhelmklopp** [comment]
Exam Update: Second one also went pretty well.

Wil - Stage 1 of 2017 exams is now complete.

**Comment by danielgavrilov** [comment]
only 2016 stages left!

**Comment by wilhelmklopp** [comment]
progress at last! 💯
